#!/usr/bin/env bash
# addons/flight-search — check the wiring. See this directory's README.md.
#
# 🔴 THIS SCRIPT INSTALLS NOTHING, and there is nothing for it to install: the
# addon is pure JS over node builtins, with no model, no index and no npm
# dependency of its own. What it needs is a CREDENTIAL, which no script may
# invent — so this reports state, prints the two lines you paste, and stops.
#
# It will never edit your .env, never enable the addon for you, and never call
# Duffel (a --check that spends a supplier call is a --check nobody runs).
#
# MODES
#   (no args)  report state and write the config stub
#   --check    report state without writing anything:
#                exit 0 — ready (a token is configured and looks like a token)
#                exit 2 — not configured yet, and configurable: get a token
#                exit 1 — configured with something that is not a Duffel token
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
STATE_DIR="${AGENT_LOCAL_DIR:-$HOME/.atlas-kit}"
SAMPLE="$STATE_DIR/flight-search.env.sample"

log() { echo "[flight-search] $*"; }

# The token is read from the environment, or — because a --check is usually run
# from a shell that never sourced it — from the repo's .env, which is where the
# operator is told to put it. Never printed, only classified.
token() {
  if [ -n "${DUFFEL_API_TOKEN:-}" ]; then
    echo "$DUFFEL_API_TOKEN"
  elif [ -f "$ROOT/.env" ]; then
    sed -n 's/^[[:space:]]*DUFFEL_API_TOKEN[[:space:]]*=[[:space:]]*//p' "$ROOT/.env" | tail -n 1 | tr -d '"'"'"'\r'
  fi
}

classify() {
  case "$1" in
    '') echo "missing" ;;
    duffel_test_*) echo "test" ;;
    duffel_live_*) echo "live" ;;
    *) echo "unrecognised" ;;
  esac
}

# Which addons this box actually runs — ATLAS_ADDONS wins whenever it is DEFINED,
# exactly as api/src/addons.mjs decides it (docs/ADDONS.md).
enabled() {
  if [ -n "${ATLAS_ADDONS+x}" ]; then
    echo "$ATLAS_ADDONS" | tr ',' '\n' | grep -qx 'flight-search' && echo yes || echo no
  elif [ -f "$ROOT/addons.json" ]; then
    grep -q '"flight-search"' "$ROOT/addons.json" && echo yes || echo no
  else
    echo no
  fi
}

write_sample() {
  mkdir -p "$STATE_DIR"
  chmod 700 "$STATE_DIR" 2>/dev/null || true
  cat > "$SAMPLE" <<EOF
# addons/flight-search — paste into the repo's .env, then \`scripts/serve.sh restart\`.
# Generated by install.sh on $(date -u +%Y-%m-%d). See addons/flight-search/README.md.

# 1. The credential. https://app.duffel.com/join → Settings → Access tokens.
#    Start with the TEST token: it is free and answers on fixed routes
#    (LHR→DXB, DXB→AMS, BTS→MRU). Real airline content needs a LIVE token.
DUFFEL_API_TOKEN=duffel_test_replace_me

# 2. Enable the addon. This line WINS over addons.json whenever it is defined —
#    list every addon this box runs, not just this one.
ATLAS_ADDONS=flight-search

# Optional. The spend bound: supplier calls per search_flights request.
# ATLAS_FLIGHTS_MAX_ADAPTER_CALLS=12
# Optional. The estimated per-ticket fee for a checked bag a fare excludes.
# ATLAS_FLIGHTS_CHECKED_BAG_FEE=55
# Optional. Connection floors, in minutes. A caller may raise these, never lower them.
# ATLAS_FLIGHTS_MIN_SELF_TRANSFER_MIN=150

# No Caddyfile block is needed: this addon registers no Express route.
EOF
  chmod 600 "$SAMPLE" 2>/dev/null || true
  log "config stub → $SAMPLE"
}

report() {
  local kind
  kind="$(classify "$(token)")"
  case "$kind" in
    test) echo "DUFFEL_API_TOKEN: a TEST token — free, and answers only on Duffel's fixed test routes" ;;
    live) echo "DUFFEL_API_TOKEN: a LIVE token — real airline content, and real Duffel billing on any order" ;;
    missing) echo "DUFFEL_API_TOKEN: not set — the tool answers with how to get one, and searches nothing" >&2 ;;
    unrecognised) echo "DUFFEL_API_TOKEN: set, but does not look like a Duffel token (expected duffel_test_… or duffel_live_…)" >&2 ;;
  esac
  echo "addon enabled on this box: $(enabled)"
}

case "${1:-}" in
  --check)
    report
    case "$(classify "$(token)")" in
      test | live) exit 0 ;;
      missing) exit 2 ;;
      *) exit 1 ;;
    esac
    ;;

  '')
    kind="$(classify "$(token)")"
    write_sample
    echo
    echo "Nothing to install — this addon has no dependency, no model and no index."
    echo "Token:         $kind"
    echo "Enabled here:  $(enabled)"
    echo
    echo "Next:"
    echo "  1. put DUFFEL_API_TOKEN in .env      (see $SAMPLE)"
    echo "  2. add flight-search to addons.json  (or to ATLAS_ADDONS)"
    echo "  3. restart:  scripts/serve.sh restart"
    echo "  4. verify:   curl -s localhost:3001/api/addons | jq '.addons[] | select(.name==\"flight-search\")'"
    ;;

  *)
    echo "usage: install.sh [--check]" >&2
    exit 2
    ;;
esac
