#!/usr/bin/env node
/* ------------------------------------------------------------------ *
 * The crontab fragment the ENABLED addons ask for.
 *
 *   node scripts/addon-cron.mjs             # print it
 *   sudo node scripts/addon-cron.mjs --install   # → /etc/cron.d/atlas-kit-addons
 *
 * WHY A HOOK AND NOT JUST A LINE IN infra/atlas-kit.cron. An addon's schedule
 * belongs to the addon: it moves when the addon's code moves, and a kit with the
 * addon disabled must not carry a cron line that fires a script it never runs.
 * So `register.mjs` DECLARES the entries and this materialises them — one file,
 * regenerated, never hand-edited, so disabling an addon and re-running removes
 * its line instead of leaving an orphan behind.
 *
 * The core cron (infra/atlas-kit.cron → /etc/cron.d/atlas-kit) is untouched and
 * stays the source of truth for the watchdog, the vault refresh and the daily
 * done-clear. This is a SECOND, separate file so the two can never clobber each
 * other, and so `--install` with zero addons enabled REMOVES the file rather
 * than writing an empty one — nothing enabled, nothing scheduled.
 * ------------------------------------------------------------------ */
import fs from 'node:fs'
import { loadAddons, addonCron, REPO_ROOT } from '../api/src/addons.mjs'
import { cronPathValue } from '../api/src/claude-bin.mjs'

const TARGET = process.env.ATLAS_ADDON_CRON_FILE || '/etc/cron.d/atlas-kit-addons'
// Every generated line runs as `root` (cron.d takes a user column), so the
// file's HOME/PATH describe ROOT's environment — not whoever ran this script.
// Same pair infra/atlas-kit.cron hardcodes.
const CRON_HOME = '/root'

await loadAddons()
const entries = addonCron()

const fragment =
  [
    '# Atlas Kit — cron entries declared by the ENABLED addons.',
    '# GENERATED by scripts/addon-cron.mjs — do not edit; re-run it instead.',
    'SHELL=/bin/bash',
    `HOME=${CRON_HOME}`,
    // ⚠️ $HOME/.local/bin is on this PATH deliberately: an addon's sweep spawns
    // `claude -p`, and cron's default PATH omits the directory `npm i -g` may
    // have installed the CLI into. Cron does not expand variables in a PATH=
    // line, so it is spelled out. Same line infra/atlas-kit.cron carries.
    `PATH=${cronPathValue(CRON_HOME)}`,
    'MAILTO=""',
    '',
    ...entries.flatMap((e) => [
      `# [${e.addon}] ${e.comment || ''}`.trimEnd(),
      // `cd` into the repo so an addon's command can stay repo-relative, and run
      // it under `root` like the core cron does. `.env` is loaded by the command
      // itself (node --env-file), never by cron.
      `${e.schedule} root cd ${REPO_ROOT} && ${e.command}`,
      '',
    ]),
  ].join('\n') + '\n'

if (process.argv.includes('--install')) {
  if (!entries.length) {
    try {
      fs.unlinkSync(TARGET)
      console.log(`removed ${TARGET} (no enabled addon declares a cron entry)`)
    } catch {
      console.log(`nothing to install (no enabled addon declares a cron entry)`)
    }
  } else {
    fs.writeFileSync(TARGET, fragment, { mode: 0o644 })
    console.log(`wrote ${TARGET} — ${entries.length} entr${entries.length === 1 ? 'y' : 'ies'}`)
  }
} else {
  process.stdout.write(entries.length ? fragment : '# no enabled addon declares a cron entry\n')
}
